<form action="<?php echo BASE_URL ?>agregar-nueva-consola"  method="POST"enctype="multipart/form-data">
    <fieldset>
        <legend>Agregue una consola</legend>

        <div class="mb-3">
            <label for="nombre">Nombre:</label>
            <input class="form-control" type="text" name="nombre" required>
        </div>
         <div class="mb-3">
            <label for="genero">Empresa:</label>
            <input class="form-control" type="text" name="empresa" required>
        </div>
       


       
        <div>
            <input type="file" name="imagen" id="imageToUpload">

        </div>

        <div>

            <button class="btn btn-success" type="submit">ENVIAR</button>
        </div>


    </fieldset>
</form>