<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
      
   <link rel="stylesheet" href="<?= BASE_URL ?>estilos/estilosNav.css">
<link rel="stylesheet" href="<?= BASE_URL ?>estilos/estilosFormUploadJuego.css">

          </head>
<body>
  
<header class="bg-dark text-white py-3 shadow-sm">
   
    <div  class="container d-flex justify-content-end align-items-center">
        
        <div >
            <?php
            if (session_status() === PHP_SESSION_NONE) {
                session_start();
            }

            if (isset($_SESSION['ID_USER'])) {
                echo '<a class="btn btn-danger" href="' . BASE_URL . 'logout">Cerrar Sesión</a>';
            } else {
                echo '<a class="btn btn-primary" href="' . BASE_URL . 'login">Iniciar Sesión</a>';
            }
            ?>
        </div>
    </div>


</header>
<!-- Navbar moderno y responsivo -->
<header class="site-header">

  <div class="container">
    <div class="logo">
      <a  href="<?php echo BASE_URL; ?>inicio">Tienda</a></a>
    </div>

    <nav class="nav-links" aria-label="Navegación principal">
      <ul>
        <li><a href="<?php echo BASE_URL; ?>inicio">inicio</a></li>
        <li><a href="<?php echo BASE_URL; ?>juegos">Juegos</a> </li>
        <li><a  href="<?php echo BASE_URL; ?>consolas">Consolas</a></li>
      </ul>
    </nav>

    <button class="menu-toggle" aria-label="Abrir menú">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
</header>
 