<!DOCTYPE html>
<html lang="es">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    </head>
<body>
    <header>
        <h1>TIENDA ONLINE</h1>
        <div>
            <a class='btn btn-danger'  href="<?php echo BASE_URL ?>logout">Cerrar Sesion</a>
             <a class='btn btn-primary'  href="<?php echo BASE_URL ?>login">Iniciar Sesion</a>
            
        </div>
</header>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<?php echo BASE_URL; ?>">Mi Tienda Gamer</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="<?php echo BASE_URL; ?>inicio">Inicio</a>
        </li>
       
        <li class="nav-item">
          <a class="nav-link" href="<?php echo BASE_URL; ?>juegos">Juegos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo BASE_URL; ?>consolas">Consolas</a>
        </li>
      </ul>
    </div>
  </div>
</nav>