<section class="bg-light text-center py-5">
  <div class="container">
    <h1 class="display-5 fw-bold mb-3">Bienvenido a Mi Tienda Gamer 🎮</h1>
    <p class="lead text-muted">
      Descubrí los mejores juegos, consolas y accesorios para vivir la experiencia gamer al máximo.  
      En nuestra tienda vas a encontrar las últimas novedades del mundo del gaming, ofertas exclusivas y reseñas imperdibles.
    </p>
    <a href="<?php echo BASE_URL; ?>juegos" class="btn btn-primary btn-lg mt-3">Explorar juegos</a>
     <a href="<?php echo BASE_URL; ?>consolas" class="btn btn-primary btn-lg mt-3">Explorar consolas</a>
  
  </div>
</section>