<?php if (!empty($mensajes)) : ?>
    <?php if (is_array($mensajes)) : ?>
        <?php foreach ($mensajes as $mensaje) : ?>
            <div class="alert alert-warning text-center my-3" role="alert">
                <?= htmlspecialchars($mensaje) ?>
            </div>
        <?php endforeach; ?>
    <?php else : ?>
        <div class="alert alert-warning text-center my-3" role="alert">
            <?= htmlspecialchars($mensajes) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
