<div>
  <p><?php $mensaje?></p>
</div>
<a href="<?php echo BASE_URL; ?>agregar-consola" class="btn btn-warning">
  Agregar Consola
</a>
<table class="table table-dark table-striped">
    <thead>
    <tr>
      <th >ID</th>
      <th >Nombre</th>
      <th>Empresa</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php
     foreach ($consolas as $consola) {
      echo "<tr>";
      echo "<th> " . $consola->id . "</th>";
      echo "<th> " . $consola->nombre . "</th>";
      echo "<th>" . $consola->empresa . "</th>";
    

    echo "<td><a  class='btn btn-danger' href=" . BASE_URL . 'eliminar-consola/' . $consola->id . ">Eliminar</a></td>";
    echo "<td><a class='btn btn-primary' href=" . BASE_URL . 'editar-consola/' . $consola->id . " >Editar</a></td>";

   
     }

       echo "</tr>";
   ?>

  </tbody>
   
</table>