

<div>
  <p><?php $mensaje?></p>
</div>

<a href="<?php echo BASE_URL; ?>agregar-juego" class="btn btn-warning">
  Agregar Juego
</a>

<table class="table table-dark table-striped">
    <thead>
    <tr>
      <th >ID</th>
      <th >Nombre</th>
      <th>Género</th>
      <th >Consola/Categoría</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php
     foreach ($juegos as $juego) {
      echo "<tr>";
      echo "<th> " . $juego->id . "</th>";
      echo "<th> " . $juego->nombre . "</th>";
      echo "<th>" . $juego->genero . "</th>";
      foreach ($consolas as $consola) {
        if ($consola->id == $juego->id_consola) {
            echo "<th>" . $consola->nombre. "</th>";

        }
      }

    echo "<td><a  class='btn btn-danger' href=" . BASE_URL . 'eliminar-juego/' . $juego->id . ">Eliminar</a></td>";
    echo "<td><a class='btn btn-primary' href=" . BASE_URL . 'editar-juego/' . $juego->id . " >Editar</a></td>";

   
     }

       echo "</tr>";
   ?>

  </tbody>
   
</table>